M48
; DRILL file {KiCad (6.0.10)} date Sun Dec 25 17:32:22 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-25T17:32:22-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
%
G90
G05
T1
X3.1949Y-4.7775
T2
X2.9862Y-4.9863
T0
M30
